server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SikGu
    username: root
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    modules:
        - com.fasterxml.jackson.datatype:jackson-datatype-jsr310
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
jwt:
  secret-key: ${jwt.secret-key}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: dyswkal5@gmail.com

logging:
  level:
    root: DEBUG