spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SikGu
    username: root
    password: yongjang5
  servlet:
    multipart:
      max-file-size: 500MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
jwt:
  secret-key: 15612135112531128931289442389489424859428951233425345
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: dyswkal5@gmail.com
logging:
  level:
    root: DEBUG
# BASE_URL 설정 추가
myapp:
#  img-path: ${IMG-PATH}
   img-path: C:\Users\SYJ\Desktop\seb43_main_002\Server\src\main\resources\static

