name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: sikgu-s3-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Add execute permission to Gradle wrapper
        run: chmod +x ./Server/gradlew
        
      - name: Build with Gradle
        run: ./Server/gradlew build
        working-directory: ./Server/
        
      - name: Make zip file
        run: zip -r ./sikgu-deploy.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_BE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BE }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./sikgu-deploy.zip s3://$S3_BUCKET_NAME/sikgu-deploy.zip

      - name: Copy application.yml
        run: cp Server/src/main/resources/application.yml build/directory
        
      - name: Build Backend
        working-directory: ./Server/
        run: ./gradlew build
